[build-system]
requires = ["hatchling==1.32.4"]
build-backend = "hatchling.build"

[project]
name = "al-falak"
version = "1.2.0"
description = "An offline library calculating prayer times"
readme = "README.md"
requires-python = ">=3.11"
authors = [{ name = "nexusnv" }]
classifiers = [
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
    "License :: OSI Approved :: MIT License",
]

[project.urls]
Homepage = "https://github.com/nexusnv/al-falak"
Documentation = "https://github.com/nexusnv/al-falak/blob/main/README.md"
Changelog = "https://github.com/nexusnv/al-falak/blob/main/CHANGES.md"

[project.scripts]
al-falak = "alfalak.__main__:main"
alfalak = "alfalak.__main__:main"

[tool.hatch.build.targets.wheel]
packages = ["src/alfalak"]

[tool.pytest.ini_options]
addopts = "--cov=alfalak --cov-branch"
testpaths = "tests"

[tool.black]
target-version = ["py311"]

[tool.mypy]
show_error_codes = true
disallow_untyped_defs = true

[tool.ruff]
target-version = "py311"

[tool.ruff.lint]
select = ["F", "E4", "E7", "E9"]